### ISSUE TITLE
Leftover merge conflict markers?

### ISSUE THREAD

**Issue by joelpurra** [binki/binki-twitch-chat-notify#2]
https://github.com/binki/binki-twitch-chat-notify/blob/dc4631ff6f5401d9c8203cd5b432529766e88980/binki-twitch-chat-notify.user.js#L88

Seems like these are leftovers from a `git stash`.

**Comment by binki** [comment]
Waaa! Probably!

This started out as a gist which I just copy and paste into Console. When I tried converting it to Greasemonkey, I didn’t get it to work (even without the merge marks?—maybe that is the issue? x.x) and still have to spend any time at all on it.

Thanks for the issue! I’ll try to find time to touch this…

**Comment by joelpurra** [comment]
Was only browsing around out of curiosity when I spotted some issues. Might try this out some day, but it won't be this year -- no rush to fix this for my sake!

**Comment by binki** [comment]
Well, that fixed the basic operation. I now have chat notifications again. Now I just have to be careful not to watch any streamers with super active/large chat communities!

**Comment by joelpurra** [comment]
The more obscure the streamer the more useful notifications are? ;)

Btw, for notifications to show, chat timestamps have to be enabled (disabled by default) in the twitch chat settings. After changing, I can confirm it works =)

**Comment by binki** [comment]
lol, correct ;-). For more busy channels, it’d be necessary to do something like keyword/pattern matching or username filtering.

Changing the display of timestamps, etc., is an issue. Thanks for checking!
